export const Endpoint = {
  Login: '/api/Login/Get',
  GetAlmacen: '/api/Consulta/Almacen',
  GetBandeja: '/api/Consulta/Bandeja',
  GetImpresoras: '/api/Consulta/GetImpresoras',
  GetTipoMovimiento: '/api/Consulta/TipoMovimiento',
  GetReqAcabadosDesdeOC: '/api/Consulta/GetReqAcabadosDesdeOC',
  GetImpresion: '/api/PreDespacho/Impresion',
  GeneratePreDespacho: '/api/PreDespacho/Generate',
  UpdatePreDespacho: '/api/PreDespacho/Update',
  DeletePreDespacho: '/api/PreDespacho/Delete',
  GetDetalle: '/api/PreDespachoDet/GetDetalle',
  GetRequerido: '/api/PreDespachoDet/GetRequerido',
  GenerateDetalle: '/api/PreDespachoDet/Generate',
  DeleteDetalle: '/api/PreDespachoDet/Delete',
  Partir: '/api/Paquete/Partir',
}
